# Use the README file as a reference to customize settings.

User:
  fields:
    default: email, password, password_confirmation
    form: email, password, password_confirmation
  application: Application
